---
csv:
  - issued_start
  - issued_finish
  - created_start
  - created_finish
  - date_other_start
  - date_other_finish

# e.g., origin_info.dateIssued.text
mods:
  - dateIssued
  - dateCreated
  - dateOther
